### ISSUE TITLE
Compilation error when folding certain servo-doubles-blocks

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#110]
While using servoblocks combined with sub-blocks, a compilation-error occurs when certain blocks are ' folded' (to take less space)

See this document for generated C-code and developertools:
[Compilatiefout - gebruik servos en subblocks.docx](https://github.com/leaphy-robotics/leaphy-blockly/files/6489437/Compilatiefout.-.gebruik.servos.en.subblocks.docx)

And this document for a screenshot and C-code of another program where three doubles-blocks are pin-pointed that give the specific error.
[Compilation error using folded doubles-blocks.docx](https://github.com/leaphy-robotics/leaphy-blockly/files/6508790/Compilation.error.using.folded.doubles-blocks.docx)

And a link to that specific  easybloqs-program-file:
https://drive.google.com/file/d/1c2BAXHzpv1jCTU91Yd_KNNTYgGuO7bZE/view?usp=sharing

**Comment by paulsiersma** [comment]
This has been fixed with #115
