### ISSUE TITLE
Option 'Show Log file' in menu 'Tips'

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#118]
EB generates a log-file in the appdata-folder>easybloqs>logs.
That's handy.

Adding a menu-option in 'tips' which actually opens the log-file (in a txt-screen or a notepad?)
would help digisuckers to copy-paste the file and post it in the forum for help.
Or e-mail it to leaphy for debug-actions.

**Comment by paulsiersma** [comment]
This should not be in the Blockly issues, and has been resolved in leaphy-client. Closing
