### ISSUE TITLE
Solving Compilation issues due to missing libraries - #1

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#192]
Sometimes compilation fails because a library-folder is already installed BUT misses a (part of) the library itself.

Apparently sometimes Easyboqs misses files during the startup-session.
And afterwards Easybloqs doesn't recognize the handicapped folder.

Solution:

 When Compilation failure is encountered, a dialogue box appears automatically:

English:
  'Compilation failed...some libraries were missing. We're updating them now!)
agree-button: >Okay, I understand<

Dutch:
  'Compilatie mislukt...bepaalde bibliotheken (libraries) ontbraken...we werken het nu bij!'
 agree-button >OK, ik begrijp het<

**Comment by ghost** [comment]
We discussed this, I think we concluded we don't want to do this at the moment. Closing, feel free to reopen.
