### ISSUE TITLE
Reset-button libraries in More-menu

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#198]
Needed:
A simple button that collects the latest libraries.
![image](https://user-images.githubusercontent.com/38002592/156342760-fda47657-74c1-44e4-a919-f18e1a4c7b96.png)

>>svg-icon<<

![Icon-library-reinstall](https://user-images.githubusercontent.com/38002592/156343067-031bacf8-50ed-4f00-8a09-872d6ffbf3e4.svg)

**Comment by ghost** [comment]
@Roelandsmith please take care to create issues in the right project. This issue has no relation to the leaphy-blockly project.

**Comment by ghost** [comment]
Fixed in [v1.1.1-pre.18](https://github.com/leaphy-robotics/leaphy-client/tree/v1.1.1-pre.18)

**Comment by Roelandsmith** [comment]
> @Roelandsmith please take care to create issues in the right project. This issue has no relation to the leaphy-blockly project.

I will do my best!

**Comment by Roelandsmith** [comment]
@paulsiersma 
 Tested it and works great!

Eén ding over de 'Toasts' die erbij horen.
Ik had voor de test expres een leaphyoriginal-librarie vernaggelt met foute code. In de leaphy original-omgeving ook getest: en ja: compilatiefout.
Daarna naar een ander robotplatform gegaan (Uno).
Dan zegt de Toast natuurlijk eerst: installing all prerequisites for Uno' 
Verrvolgens heb ik in die toolbox op de 'restore libraries' gedrukt.
Dan zegt de Toast weer: 'installing all prerequisites for Uno' (Maar hij doet nu natuurlijk meer dan bij het gewone inladen)

Daarna ging ik terug naar LEaphy Original-robot-toolbox.
En dan opnieuw de code getest: compilatie geslaagd. (Dus de restore-button werkt idd voor alle libaries, ongeacht vanuit wel robotplatform je hem activeert. Maar: de bijbehorende Toast doet anders vermoeden. 
Want de Toast zegt in dit geval: 'installing for Uno'
Maar wat hij eigenlijk doet is: 'Restoring all Libraries'

Het zou mooi zijn om dat aan te passen:
Dat hij bij deze restore- button altijd in de Toast zegt: 'Restoring all libraries'
'Alle bibliotheken herstellen' (ongeacht vanuit welke robot-toolbox je hem aanklikt)

Dan kan de gebruik er ook zien dat het veelomvattender is dan het reguliere 'installing prerequisites' bij het openen van een Robot-toolbox.
