### ISSUE TITLE
Number block True and False always False

### ISSUE THREAD

**Issue by beekumo** [leaphy-robotics/leaphy-blockly#254]
Testing the beta version (okt 2022)
When number block is set to 1 (High) in C code remains 0 (Low)
![WhatsApp Image 2022-11-05 at 10 14 54](https://user-images.githubusercontent.com/99642617/200112910-c04277f3-b9e0-4b2f-899e-49cd40494703.jpeg)

**Comment by JeftadeGraaf** [comment]
Fixed with commit 9a32ce9e6e5ea6d0c812f3edaf22c040d9d176fb
