### ISSUE TITLE
Ledstrip number always 0

### ISSUE THREAD

**Issue by beekumo** [leaphy-robotics/leaphy-blockly#257]
![WhatsApp Image 2022-11-12 at 15 25 25](https://user-images.githubusercontent.com/99642617/201478809-ba203082-1677-4f50-92ce-04a3485dcd08.jpeg)

Assignment of a Led in the Ledstrip not functioning. For example, when assigning led number 3 the number remains 0, also see the picture in the attachment.

**Comment by JeftadeGraaf** [comment]
Issue has been fixed, will close it for now
