### ISSUE TITLE
Replace trash can with treasure chest

### ISSUE THREAD

**Issue by paulsiersma** [leaphy-robotics/leaphy-blockly#55]
https://drive.google.com/drive/folders/1oqU1z-Jx8OMtLPy3guvi7nzl9TwUxZbj?usp=sharing

**Comment by JeftadeGraaf** [comment]
Please provide working drive link. This link takes me to an empty folder.

**Comment by paulsiersma** [comment]
This was shared with me by Jort. He is no longer sharing it with me, so I can't provide you with it.

**Comment by koen1711** [comment]
Nothing to do here, reopen when provided a good example.
