### ISSUE TITLE
Decrease space between blocks in toolboxes

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#60]
The space between the blocks in de the toolboxes is uit quite big. (See below)
Making it a bit less high, gives the user more blocks in 1 screen. (See 2nd mBlock-image for comparison)

![image](https://user-images.githubusercontent.com/38002592/108213742-a7f22d00-712f-11eb-8449-6c48f4dffffd.png)

![image](https://user-images.githubusercontent.com/38002592/108213982-e851ab00-712f-11eb-9320-f58ed6d890f3.png)

**Comment by paulsiersma** [comment]
This is actually to be fixed in Easybloqs. Moved to https://github.com/leaphy-robotics/leaphy-client/issues/65
