### ISSUE TITLE
Multiple select-option for duplicating blocks

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#65]
![image](https://user-images.githubusercontent.com/38002592/109299493-7e26bd80-7835-11eb-895a-3c5f161d3732.png)

**Comment by paulsiersma** [comment]
@Roelandsmith I don't think this is feasible unless it is added as a feature by google/blockly. You could put them in a containing block as you say and then duplicate. Maybe this is a feature in disguise: Code duplication is considered a "code smell". If you feel the need to duplicate blocks, maybe what you really need is a function?
