### ISSUE TITLE
Every robot-toolbox needs its own "Extra" toolbox

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#70]
This document has all information needed:
[Toolboxes Easybloqs - 15 maart.docx](https://github.com/leaphy-robotics/leaphy-blockly/files/6086531/Toolboxes.Easybloqs.-.15.maart.docx)

**Comment by paulsiersma** [comment]
Closing, moved to https://github.com/leaphy-robotics/leaphy-client/issues/91
