### ISSUE TITLE
Block-Variable shows in Code-field as HEX(?)

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#77]
In a block, the variable has the 'right' name, but in the code editor it changes to HEX (I think)
It would help the beginning code-writer if the same name as in the block was used.

![image](https://user-images.githubusercontent.com/38002592/112057104-25f38a80-8b59-11eb-982a-19bd7e802375.png)

**Comment by paulsiersma** [comment]
This is fixed!
