### ISSUE TITLE
New Leaphy Toolbox Category: Leaphy Click

### ISSUE THREAD

**Issue by paulsiersma** [leaphy-robotics/leaphy-blockly#81]
We need a new toolbox category for Leaphy Click. This means adding a String for `%{BKY_LEAPHY_CLICK_CATEGORY}` and making sure the toolbox category icon is present and bundled.

**Comment by Roelandsmith** [comment]
Thiw week (last week of march) I will add one more blockdescription for Leaphy click, because the designer of the Clickjort had a nice idea for adding a RGB-led on the robotarm Clickjort. We will make one special block for that option.
