### ISSUE TITLE
Adding sinus-cosinus and other math-blocks to 'Getalblokken' toolbox

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#88]
Needed for smooth motion with Servo's...
The block was there, but I think we took it out for more simplicity...
They can be placed at the bottom of the light green blocks-toolbox-list.
But now we needed for High school projects!

In Blockly itself they look like this:
![image](https://user-images.githubusercontent.com/38002592/113593438-b8565c80-9636-11eb-9db9-938257b47b9c.png)

**Comment by paulsiersma** [comment]
Fixed in #103
