### ISSUE TITLE
Leaphy Click - text in Motor block 'Motor_L' must be replaced by 'Motor A'

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#89]
Motor_L and Motor_B are great for the Original-robot. For the Click platform, the output-annotation on the Shield is more handy: 'Motor_A'

It's only an manner of chaning the text in the block...the rest of the code remains the same (I assume)

![image](https://user-images.githubusercontent.com/38002592/113594591-31a27f00-9638-11eb-906c-cabc757725d0.png)

**Comment by paulsiersma** [comment]
Fixed with #103
