### ISSUE TITLE
Leaphy click toolbox - create RGB- digipin-block

### ISSUE THREAD

**Issue by Roelandsmith** [leaphy-robotics/leaphy-blockly#91]
A threefold digipin-write block which enables turning on and off the three colours of the clickort LED
Default pins: 11, 12 & 13 (If possible, otherwise three times '2' will do)
![image](https://user-images.githubusercontent.com/38002592/113757579-0d67a080-9713-11eb-8baf-d33ef8670dec.png)

**Comment by paulsiersma** [comment]
Fixed in #103
